### ISSUE TITLE
D compiler 

### ISSUE THREAD

**Issue by captain-sensible** [aberba/learn-coding#1]
had a look at book , but really need to run your code examples. You probably know Slackware users are extremely sensible people ( some might interpret that as control freaks) any way on Slackware we don't use "make" etc instead we use a Slackbuild script that creates a clean package. So you can add this link https://slackbuilds.org/repository/14.2/development/dmd/ so Slackers can get the compiler - i havn't built
package yet.  

## Introduction to computer programming
A computer is an electronic device which takes instructions and do it.

You could say "A computer is an electonic device, which takes instructions & carries them out.

Typo's: robortics

You could mention that an easy distinction bewtween a computer & a text editor which is a software program that has a Graphic user Interface GUI, is this.if you drop it on your foot & it hurts like a PC Tower- its "hardware" if not its software

**Comment by aberba** [comment]
Thanks for reading. Will look into your corrections.

**Comment by aberba** [comment]
I try to ignore certain details cus I assum they might confuse the reader (newbie). They will be explained later in the book at the right time.
