### ISSUE TITLE
Windows Source Folder

### ISSUE THREAD

**Issue by hardliner66** [aberba/learn-coding#2]
The source folder on windows should not be "C:\D\" because this is the folder where the compiler and standard libs are stored.

The code should be in a newly create folder in the home directory (like described in the linux part) or somewhere like "C:\projects".

**Comment by aberba** [comment]
Ok. Hope telling users to enter `cd C:\projects` will not scare them. But I think that's the right thing to do.

**Comment by hardliner66** [comment]
Use the explorer.
Shift + Right Click -> Open Command Prompt here

dmd should be automatically added to the path on windows, so that shouldn't be a problem.

**Comment by aberba** [comment]
Is dmd path added? A friend of my was try but did not work for him Win 10.

**Comment by hardliner66** [comment]
![image](https://cloud.githubusercontent.com/assets/2937272/23017126/613929ee-f439-11e6-8c32-f02eb342e5f0.png)

There is an option "Add to PATH" which is enabled by default.

**Comment by aberba** [comment]
I'm pushing an update now. Let me know what you think (on the issues yoy raised).

**Comment by hardliner66** [comment]
I still think, that the D2 32-bit Command Prompt is not needed and you should plain cmd instead. maybe with a hint to keep the option "Add to PATH" checked.

But the path part is okay.
