### ISSUE TITLE
Don't use ./ to execute binaries on windows

### ISSUE THREAD

**Issue by hardliner66** [aberba/learn-coding#3]
On windows you will get an error, if you use ./try.exe like in your example.

use the following instead
try.exe

**Comment by aberba** [comment]
Yeah thanks. One thing about testing in Linux :smile:

**Comment by hardliner66** [comment]
Thats probably one of the best things about windows 10. You can use the windows cmd, powershall and bash for linux 😃

**Comment by aberba** [comment]
Done.
