### ISSUE TITLE
Rename try.d to hello.d

### ISSUE THREAD

**Issue by hardliner66** [aberba/learn-coding#4]
Because this is a hello world application, the file should be named accordingly. (hello.d)

Or name it main.d because it is the main entry point for the application (or app.d, if you want to use the default name from dub projects)

**Comment by aberba** [comment]
Thanks. was using that file to run the code and forgot to ignore it. 

That reminds me, I need to include source code in an `examples` folder

**Comment by hardliner66** [comment]
The examples folder is a good idea. You should consider using chapters or categories in your description (numbered) and name the subfolders in examples accordingly.

**Comment by aberba** [comment]
Ok. Doing it now

**Comment by aberba** [comment]
Done. Updated the intro
